apiVersion: batch/v1
kind: Job
metadata:
  name: "initbilldb"
  namespace: bill
spec:
  template:
    metadata:
      name: "initbilldb"
    spec:
      restartPolicy: OnFailure
#      initContainers:
#        - name: check-db-ready
#          image: postgres:13.1-alpine
#          env:
#            - name: POSTGRES_HOST
#              value: "postgres"
#            - name: POSTGRES_PORT
#              value: "5432"
#          command:
#            - sh
#            - "-c"
#            - |
#              until pg_isready -h $POSTGRES_HOST  -p  $POSTGRES_PORT;
#              do echo waiting for database; sleep 2; done;
      containers:
      - name: initdb
        image: postgres:13.1-alpine
        env:
          - name: DATABASE_URI            
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: DATABASE_URL 
        command:
          - sh
          - "-c"
          - |
            psql $DATABASE_URI <<'EOF'
             DROP table IF EXISTS letters;




             create table letters (  id serial primary key,
                                   to_ varchar(50),
                                   message_ varchar(200)

             );
            insert into letters (id, to_, message_)
            values
            (1,'ivan@1.com', 'good'),
            (2,'nina@1.com', 'bad');

  EOF
  backoffLimit: 3