apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: app
data:
  DB_NAME: users   
  SPRING_DATASOURCE_URL: jdbc:postgresql://nf:5434/letters
  DB_HOST: nf
  spring.jpa.hibernate.ddl-auto: create
  spring.datasource.driver-class-name: org.postgresql.Driver
  spring.jpa.database: postgresql
  spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  spring.datasource.initialization-mode: ALWAYS
  

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  #POSTGRESQL_USERNAME: ZGJ1c2Vy
  postgresql-password: cm9vdA==
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnJvb3RAcG9zdGdyZXM6NTQzMy91c2Vycw==
